import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Sidebar } from "@/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <div className="flex h-screen">
          <div className="md:w-64 flex-shrink-0">
            <Sidebar />
          </div>
          <main className="flex-1 bg-gray-50">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
