import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Sidebar } from "@/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row h-screen">
          <div className="md:w-64 w-0">
            <Sidebar />
          </div>
          <div className="flex-1">
            <Providers>{children}</Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
